# This workflow crawls nepal police website for news once a day and write the news content ass json.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Crawl nepal police website for news every day exactly at 11 AM (With assuming govt office open at 10, so they upload news till 11)

on:
  schedule:
  - cron: '0 11 * * *'
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Python
        uses: actions/setup-python@v4.7.0
      
      - name: Install packages from PIP
        run: pip install -r requirements.txt

      - name: Execute crawler script
        run: ./extract_nepali_crime_news.py

      - name: Prepare git config
        run: git config --global user.email "runner@github.com" && git config --global user.name "Github Action Runner"

      - name: Commit the change
        run: git add --all && git commit -m "Crawled on $(date)"

      - name: Push new file
        run: git push
